moocb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from moocb.views import home, login_user, me, logout_user, add_time, add_user, add_goal, login_user_json, select_goal, add_incentive, pay
from django.conf import settings
from django.views.generic import TemplateView


admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'moocb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', me),
    url(r'^login/$', login_user),
    url(r'^logout/$', logout_user),
    url(r'^me/$', me),
    url(r'^add/$', add_time),
    url(r'^adduser/$', add_user),
    url(r'^addgoal/$', add_goal),
    url(r'^addincentive/$', add_incentive),
    url(r'^login_json/$', login_user_json),
    url(r'^select_goal/$', select_goal),
    url(r'^pay/$', pay),
  

     url(r'^google6f82ca7c7de8dd2c.html/$', TemplateView.as_view(template_name='moocb/google6f82ca7c7de8dd2c.html'), name="home"),
      url(r'^google7c1c3385afed65d5.html/$', TemplateView.as_view(template_name='moocb/google7c1c3385afed65d5.html'), name="home"),

)


urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

moocb/models.py
from django.db import models
from djangotoolbox.fields import ListField
from moocb import settings



from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from datetime import datetime, timedelta

# Create your models here.
class Subscriber(models.Model):
	email_address = models.EmailField(unique=True)

	def __unicode__(self):
		return u'%s' % (self.email_address)	

class UserInfo(models.Model):
    user = models.OneToOneField(User)
    goal = models.CharField(max_length=300)
    def __unicode__(self):
    	return u'%s' % (self.user)	

def get_end():
	return datetime.today() + timedelta(days=80)

class Goal(models.Model):
	user = models.OneToOneField(User)

	name = models.CharField(max_length=300)
	url = models.URLField(max_length=300)
	
	#time_goal is the hrs to be worked per week
	time_goal = models.PositiveIntegerField( null=True)

	start_date = models.DateField(default=datetime.now)
	end_date = models.DateField(default=get_end)
	time_worked = models.PositiveIntegerField(default=0)

	last_worked = models.DateField(blank=True, null=True)

	
	def __unicode__(self):
		return u'%s' % (self.name)	




class Incentive(models.Model):
	goal = models.OneToOneField(Goal)

	#
	total_pledge = models.PositiveIntegerField(default=3000)
	amount_refunded = models.PositiveIntegerField(default= 0)

	refund_increment = models.FloatField(default= 0.25, validators = [MinValueValidator(0.0),])

	is_paid = models.BooleanField(default=False)



	def __unicode__(self):
		return u'Incentive for %s: %s' % (self.goal.name, self.total_pledge)


	@property
	def total_dollars(self):
		return '%.2f' % ( self.total_pledge / 100.0)




class TimeLog(models.Model):
	
	goal = models.ForeignKey(Goal)

	date = models.DateField(default=datetime.now)
	time_to_add = models.PositiveIntegerField()

	def __unicode__(self):
		return u'%s : %s : time added: %d' % (self.goal.name, self.date, self.time_to_add)	

	class Meta:
		ordering = ["date"]

moocb/forms.py
from django.contrib.auth.models import User
from moocb.models import  Goal, Incentive, get_end
from django.forms import ModelForm
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.utils.safestring import mark_safe
from django.forms import widgets

class UserWidget(widgets.TextInput):
    def render(self, name, value, attrs=None):
        return mark_safe(u'''<div class="entry container">
								
								<div class="col-xs-2">
								    <img class='form-pic' src="/static/moocb/email.png">

								</div>
								  
								<div class="col-xs-10">%s</div>
						    </div>


     ''' % (super(UserWidget, self).render(name, value, attrs)))

class PasswordWidget(widgets.TextInput):
    def render(self, name, value, attrs=None):
        return mark_safe(u'''<div class="entry container">
								
								<div class="col-xs-2">
								    <img class='form-pic' src="/static/moocb/lock.png">

								</div>
								  
								<div class="col-xs-10">%s</div>
						    </div>


     ''' % (super(PasswordWidget, self).render(name, value, attrs)))

class IncentiveWidget(widgets.TextInput):
    def render(self, name, value, attrs=None):
        return mark_safe(u'''<div class="entry container">
								
								<div class="col-xs-2">
								    <img class='form-pic' src="/static/moocb/dolla.png">

								</div>
								  
								<div class="col-xs-10">%s</div>
						    </div>


     ''' % (super(IncentiveWidget, self).render(name, value, attrs)))




class UserForm(ModelForm):
	
	class Meta:
		model = User
		fields = ( 'email', 'password')
	#username = forms.CharField( widget=forms.TextInput(attrs={'placeholder': 'username', 'class': 'text-center form-control entry'}))
	email = forms.CharField(widget=UserWidget(attrs={'placeholder': 'email', 'class': 'form-control text-center entry-2'}))
	password = forms.CharField(widget=PasswordWidget(attrs={'placeholder': 'password', 'type': 'password', 'class': 'form-control text-center entry-2'}))

class GoalForm(ModelForm):
	class Meta:
		model = Goal
		fields = ( 'url', 'time_goal', 'end_date', )
	#name = forms.CharField( widget=forms.TextInput(attrs={'placeholder': 'name your course', 'class': 'text-center form-control entry'}))
	url= forms.CharField( widget=forms.TextInput(attrs={'placeholder': 'copy and paste the exact url of course', 'class': 'text-center form-control entry'}))
	end_date =  forms.DateField(widget=SelectDateWidget(attrs={'class': 'form-control entry date-entry text-center'} ),initial= get_end)
	time_goal = forms.CharField( widget=forms.TextInput(attrs={ 'class': 'text-center form-control entry-small'}), initial= 5)


class IncentiveForm(ModelForm):
	class Meta:
		model = Incentive
		fields = ( 'total_pledge',)
	total_pledge = forms.IntegerField(widget=IncentiveWidget(attrs={'placeholder': 'Enter a Dollar value', 'class': 'text-center form-control entry-2'}))
	



		

moocb/views.py
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.shortcuts import render_to_response

# from django.http import *
# from django.shortcuts import render_to_response,redirect
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from moocb.models import Goal , User, TimeLog, Incentive
import json
from forms import UserForm, GoalForm, IncentiveForm
import sys
from django.core import serializers
import stripe
from moocb.timekeeper import addTime



def home(request):
    
    return render_to_response('moocb/home2.html')


def login_user(request):
    logout(request)
    username = ''
    password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        print user
        if user is not None:
            if user.is_active:
                login(request, user)
                if (Goal.objects.filter(user = user)):
                    return HttpResponseRedirect('/addgoal/')
                else:
                    return HttpResponseRedirect('/me/')
    return render_to_response('moocb/login.html', context_instance=RequestContext(request))


@csrf_exempt
def login_user_json(request):
    try:
        logout(request)
        username = 'ben'
        password = '1'
        print request.POST
       
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        user = authenticate(username=username, password=password)
        print user
        if user is not None:
            if user.is_active:
                login(request, user)
                goal = Goal.objects.filter(user = user)[0]
                data = {
                    'type': 'user_login',
                    'status': 'success',
                    'user': user.username,
                    'userid': user.id,
                    'goal': {
                            'name': goal.name, 
                            'id': goal.id,
                            'url': goal.url,
                            'time_goal': goal.time_goal,
                            'last_worked': goal.last_worked,
                            'start_date': str(goal.start_date),
                            'end_date': str(goal.end_date),
                            'time_worked': goal.time_worked,
                            },
                }


                return HttpResponse(json.dumps(data), content_type="application/json")
        data = {
            'type': 'user_login',
            'status': 'fail',
            'msg' :'non fatal inval login. is it an active user?',
        }
        return HttpResponse(json.dumps(data), content_type="application/json")
    except:
        data = {
           'type': 'user_login',
           'status': 'fail',
           'msg' : str(sys.exc_info()[0] ),
        }
        
        
        return HttpResponse(json.dumps(data), content_type="application/json")

@csrf_exempt
def select_goal(request):
    context = RequestContext(request)
    try:
        if request.user.is_authenticated():
            data = {'user': request.user.id }
        else:
            data = {'msg' : 'user not found?'}
        return HttpResponse(json.dumps(data), content_type="application/json")

    except:
        data = {'msg': str(sys.exc_info()[0] )}

    return HttpResponse(json.dumps(data), content_type="application/json")



@login_required
def me(request):


    try:
        context = RequestContext(request)

        context['user'] = request.user
        
        context['goal'] = Goal.objects.get(user = request.user.id)
        context['incentive'] = Incentive.objects.get(goal = context['goal'])
        context['time_logs'] = TimeLog.objects.filter(goal = context['goal'])
        return render_to_response('moocb/me.html', context)
    except:
       return HttpResponseRedirect('/addgoal/')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/login/')

@csrf_exempt
def add_time(request):
    
    context = RequestContext(request)
    print request
    print 'calling add time view' , request.POST #, (request.Post == True)
    data = {}
    if request.POST:

        print "post detected!"
        
       
        try:
            print "getting user id"
            user_id =  request.GET.get('user', None)
            print "getting goal id"
            goal_id = request.GET.get('goal', None)
            print "getting time id"
            time = request.GET.get('time', None)
            print 'user_id :', user_id, 'goal_id ', goal_id, 'time ', time
            print user_id and goal_id and time
            print 'pixxa'
            if user_id and goal_id and time:
                print 'if statement running'
                user = User.objects.get(id=user_id)
                print user
                goal = Goal.objects.get(id=goal_id)
                print "user", user, 'goal', goal
                print 'goal user', goal.user

                if goal.user.id == user.id:
                    print "goal time", goal.time_worked
                    goal.time_worked = goal.time_worked + int(time)
                    goal.save()
                    addTime(goal, int(time))
                    print " new goal time", goal.time_worked
                    time_left = goal.time_goal - goal.time_worked

                    data = {
                    'goal' : goal.name, 
                    'time_added' : time,
                    'new_goal_time': goal.time_worked,
                    'time_left_to_goal' : time_left,
                    'user' : user.username,
                    }
                else:
                    data = {'msg': 'goal and id dont match '}
                    print "goal and id dont match "
               

             
            else:
                data = {'msg': 'not enough parameters included, make sure to include user goal and time'}
                print "not true"
            print 'after loop'

        except:
            print 'error'
            data = {'msg': str(sys.exc_info()[0] )}

        print 'pre return'
      
        
    else:
        raise Http404
    return HttpResponse(json.dumps(data), content_type="application/json")

        
    # 5483c154c5cbe516f21d5f08
    # 5483d7bec5cbe518fe34eb84
    # 5483d889c5cbe5190bc1d834

    # context['time'] = request.GET.get('time', 'no time found' )
    # context['user_id'] = request.user.id
   
    # return render_to_response('moocb/add.html', context)



def add_user(request):
    context = RequestContext(request)
    logout(request)
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(username = form.cleaned_data['email'], **form.cleaned_data)
            print new_user
            print "form data"
            #print 'form username' , form.cleaned_data['username']
            print 'form pw' , form.cleaned_data['password']
            #new_user = authenticate(username='ben', password='1')

            print 'new_user object ' , new_user
            print request
            #hack!
            new_user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, new_user)

            # redirect, or however you want to get to the main vie
            return HttpResponseRedirect('/addgoal/')
            #return render_to_response('moocb/me.html', context_instance=RequestContext(request))
    else:
        form = UserForm() 
    return render_to_response( 'moocb/adduser.html', {'form': form},  context_instance=RequestContext(request))

@login_required
def add_goal (request):

    context = RequestContext(request)
    context['user'] = request.user
    if (Goal.objects.filter(user = request.user.id)):
        if Incentive.objects.filter(goal__user = request.user.id):
            return HttpResponseRedirect('/me/')
        else:
            return HttpResponseRedirect('/addincentive/')

    else:
        if request.method == "POST":
            form = GoalForm(request.POST)
            if form.is_valid():

                new_goal = Goal(user= request.user, **form.cleaned_data)
                print "modifying goal"
                
                new_goal.time_goal = int(new_goal.time_goal) * 60 * 24 * 7 
                print  new_goal.time_goal
                new_goal.save()
                return HttpResponseRedirect('/addincentive/')
        else:
            form = GoalForm() 

    return render_to_response( 'moocb/addgoal.html', {'form': form},  context_instance=RequestContext(request))

@login_required
def add_incentive(request):
    context = RequestContext(request)

    context['user'] = request.user
    goal = Goal.objects.filter(user = request.user.id)[0]
    try: 
        incentive = Incentive.objects.filter(goal__user = request.user.id)[0]
    except:
        incentive = None    
    if request.method == "POST":
        print request.POST
        if incentive != None:
            print 'incentive', incentive
            form = GoalForm(request.POST)
        
        form = IncentiveForm(request.POST)
        if form.is_valid():
            print 'no incentive'
            print form.data 
           
            new_incentive = Incentive(goal = goal, **form.cleaned_data)
            #modify incentive to be right for $$$$$
            new_incentive.total_pledge = new_incentive.total_pledge * 100
            new_incentive.save()
            # new_goal = Goal (user= request.user, **form.cleaned_data)
            # new_goal.save()
            if 'no_pay' in request.POST:
                return HttpResponseRedirect('/me/')
            elif 'pay' in request.POST:
                return HttpResponseRedirect('/pay')
            else:
                pass

moocb/templates/moocb/add.html
<html>

<head>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
	{% load staticfiles %}
	<link href="{% static "moocb/moocb.css" %}" rel="stylesheet">
</head>




<body>


	<h1 class = 'text-center'>User {{user}}</h1>

	<h1 class = 'text-center'>User id {{user_id}}</h1>


	<h1 class = 'text-center'></h1>
	<h1 class = 'text-center'>Time: {{time}}</h1>
	<h1 class = 'text-center'>Course: {{course.url}}</h1>
	<h1 class = 'text-center'>Course: {{course.start_date}}</h1>
	<h1 class = 'text-center'>Course: {{course.time_worked}}</h1>


	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>


</html>

moocb/templates/moocb/addgoal.html
{% extends 'base.html' %}

{% block content %}


<div class = 'form text-center'>
	<h3 class = 'form-title '>Welcome!</h3>
	<h2>What course are you taking?</h2>

	
	<form method="post" action="">
		{% csrf_token %}
		{% for field in form %}
			{% if field.errors %}
						{% for error in field.errors %}
	       			
	   					<div class="alert alert-danger " role="alert">{{ error|escape }}</div>

						{% endfor %}
			{% endif %}

			{% if field.name == 'url' %}
				{{field}}
			
				
			{% endif %}

			

			{% if field.name == 'time_goal' %}
				<p>I pledge:</p>
				{{field}}
				<p>Hours Per week to completing this course.</p>
				<p>[*you will be paid for every <strong id="hours-span">5</strong> hours you complete]</p>
		
				
			{% endif %}


			{% if field.name == 'end_date' %}
				<br>
				<p>I'll start <strong>today</strong> and finish on:</p>
				{{field}}
			{% endif %}

			
		
		{% endfor %}
		
			
	   
			<input class = 'submit' type="submit" value="pledge" />

	</form>



{% endblock %}



{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){ 
	$('#id_time_goal' )
	  .change(function () {
	   console.log('new val' , $('#id_time_goal' ).val())

	$("#hours-span").html( $('#id_time_goal' ).val() )


	  })

  })



</script>
{% endblock %}

moocb/templates/moocb/addincentive.html
{% extends 'base.html' %}

{% block content %}


<div class = 'form text-center'>
	<h3 class = 'form-title '>Welcome, {{user}}!</h3>
	<p>How much money will you pledge to finishing your course?</p>
	
	<form method="post" action="">
		{% csrf_token %}
		{% for field in form %}
			{% if field.errors %}
						{% for error in field.errors %}
	       			
	   					<div class="alert alert-danger " role="alert">{{ error|escape }}</div>

						{% endfor %}
			{% endif %}


		
			{{field}}
		{% endfor %}
		
			
	   
			<input name = "no_pay" class = 'submit' type="submit" value="create" />
			<input name = "pay"class = 'submit' type="submit" value="create and pay" />
	</form>








{% endblock %}

moocb/templates/moocb/adduser.html
{% extends 'base.html' %}

{% block content %}


<div class = 'form text-center'>
	<h3 class = 'form-title '>Create your Moocbuddy account</h3>

	<form method="post" action="">
		{% csrf_token %}
			{% for field in form %}
				{% if field.errors %}
					{% for error in field.errors %}
       			
   					<div class="alert alert-danger " role="alert">{{ error|escape }}</div>

					{% endfor %}
		      	{% endif %}

	      		{{field}}

	   		{% endfor %}
	   
			<input class = 'submit' type="submit" value="create" />

	</form>




{% endblock %}



{% block scripts %} 
{% load staticfiles %}
	<script src="{% static "moocb/form.js" %}"></script>

{% endblock %}


	

moocb/templates/moocb/google6f82ca7c7de8dd2c.html
google-site-verification: google6f82ca7c7de8dd2c.html

moocb/templates/moocb/google7c1c3385afed65d5.html
google-site-verification: google7c1c3385afed65d5.html

moocb/templates/moocb/home.html
<html>

<head>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
	{% load staticfiles %}
	<link href="{% static "moocb/moocb.css" %}" rel="stylesheet">
</head>




<body>


	<h1 class = 'text-center'>We help you finish what you start.</h1>
	<p class = 'text-center'>Hey, I'm your Moocbuddy. Remember that class you've always wanted to take?<strong> Let's do this.</strong></p>

	<div class = "row text-center">
		<div class = "col-xs-4">
			<p><strong>Select</strong><br>Your Course</p>
			
		</div>
		<div class = "col-xs-4">
			<p><strong>Motivate</strong><br>Yourself</p>
			
		</div>
		<div class = "col-xs-4">
			<p><strong>Finish</strong><br>What you start.</p>
			
		</div>
	</div>
	<div class= "text-center">
		<button class= " btn-large"> Go </button>
	</div>



	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>


</html>

moocb/templates/moocb/home2.html
{% extends "base.html" %}


{% block content %} 


<h1>HELLO</h1>


{% endblock %}

moocb/templates/moocb/login.html
<html>

<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    {% load staticfiles %}
    <link href="{% static "moocb/moocb.css" %}" rel="stylesheet">
</head>




<body>


    <div id="login">
        <form class="form-horizontal" name="LoginForm" action="/login/" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}
        <div class="control-group">
            <label class="control-label" for="username">Username</label>
            <div class="controls">
                <input type="text" id="username" name="username"  placeholder="Username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="password">Password</label>
            <div class="controls">
                <input type="password" name="password" id="password" placeholder="Password">
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Login</button>
            </div>
        </div>
        </form>
    </div>

    
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>


    </html>

moocb/templates/moocb/me.html
<html>

<head>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
	{% load staticfiles %}
	<link href="{% static "moocb/moocb.css" %}" rel="stylesheet">
	<link href="{% static "moocb/bootstrap.min.css" %}" rel="stylesheet">
	 <link rel="chrome-webstore-item"
    href="https://chrome.google.com/webstore/detail/milcfngfomdmcongnpglkdlgkodjcfdl">

</head>




<body>

	<h1 class = 'text-center'>Hi {{user}}</h1>
	
 <a href = 'https://chrome.google.com/webstore/detail/moocmate-extension/milcfngfomdmcongnpglkdlgkodjcfdl'> Install the chrome extension to get started!</a>



	<h1>Goals:{{goal}}</h1>
	<h1>TimeLogs:{{time_logs}}</h1>
	<h1>Incentive: {{incentive}}</h1>
	<h2>Incentive paid? {{incentive.is_paid}}</h2>

{% if incentive.is_paid == False %}
	<form action="/pay/" method="POST">
		{% csrf_token %}
	  <script
	    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	    data-key="pk_test_ac0EQFgbU0C6zzVpQXHbGSi0"
	    {% load staticfiles%}
	    data-image="{% static "moocb/icon.jpg" %}"
	    data-name="Moocbuddy"
	    data-description="${{incentive.total_dollars}} deposit on finishing my online class."
	    data-amount="{{incentive.total_pledge}}"
	  </script>
	</form>
{% endif %}


<button onclick="chrome.webstore.install()" id="install-button" class = "chrome-install">Add to Chrome</button>
<script>
if (chrome.app.isInstalled) {
  document.getElementById('install-button').style.display = 'none';
}
</script>




	<div class = ' text-center jumbotron dashboard'>
		<h3 class = ''> Goal Progress for {{goal.url}}</h3>
		<div class = 'row'>
			<div class = 'col-xs-6'>
				<h4>Total Time Worked : {{goal.time_worked}}</h4>
				<h4>Total Time Goal : {{goal.time_goal}}</h4>
				<h4 class= 'percent_completed'>Percentage Completed : </h4>

			</div>

			<div class = 'col-xs-6 time_logs'>
				<h4>My Time Logs</h4>
				<ul>
				{% for time_log in time_logs %}
					<li>{{time_log}}</li>
				{% endfor %}
				</ul>

			

			</div>






		</div>




	</div>
	



	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
	{% load staticfiles %}
	<script src="{% static "moocb/jquery-1.11.1.min.js" %}"></script>
	<script src="{% static "moocb/bootstrap.min.js" %}"></script>

	
	<script type="text/javascript">
	{% block content %}
	var time_goal = {{goal.time_goal}};
	var time_worked= {{goal.time_worked}};
	var percent_completed = (time_goal - (time_goal - time_worked)) * 100 / time_goal;

	//var time_logs = {{time_logs}};

	$(".percent_completed").append(percent_completed + '%');

	{% endblock  %}

	$(".chrome-install").click(function() {
		
		// e.preventDefault();
		console.log('installing now')
		chrome.webstore.install('https://chrome.google.com/webstore/detail/pcdjfmagbablokdcbjpffipnicphamob', 
                      function(){ alert("Sucess");},
                      function(detail){ alert("Failure:"+detail);});
	});

	</script>

	
</body>


</html>

moocb/templates/moocb/pay.html
{% extends 'base.html' %}

{% block content %}


<div class = 'form text-center'>
	<h3 class = 'form-title '>Welcome, {{user}}!</h3>
	<p>Let's Pay! ${{incentive.total_dollars}}</p>
	
	
	

	<form action="" method="POST">
		{% csrf_token %}
	  <script
	    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	    data-key="pk_test_ac0EQFgbU0C6zzVpQXHbGSi0"
	    {% load staticfiles%}
	    data-image="{% static "moocb/icon.jpg" %}"
	    data-name="Moocbuddy"
	    data-description="${{incentive.total_dollars}} deposit on finishing my online class."
	    data-amount="{{incentive.total_pledge}}">
	  </script>
	</form>
</div>
<div class = "text-center">
<a class="btn text-center btn-default" href="/me/" role="button">Back to Profile</a>
</div>
{% endblock %}